name: todo_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_auth:
  cloud_firestore:
  firebase_core:
  connectivity_plus:
  image_picker:
#  image_crop:
#  image_cropper:
  flutter_image_compress:
  firebase_storage:
  local_auth:
  carousel_slider:
  cached_network_image:
  chewie:
  video_player: ^2.2.5


  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

